version: '3'
services:
  db:
    image: mysql:5.7
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    # ports:
      # - 3307:3306
  wp:
    # image: wordpress:cli-php7.3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    command: "vendor/bin/phpunit"

